version: '3.8'
services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "composer install --ignore-platform-reqs && php artisan route:clear && php artisan serve --host=0.0.0.0"
    volumes:
      - .:/app
    ports:
      - 8001:8000
    depends_on:
      - db

  queue:
    container_name: main-queue
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: main-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    ports:
      - 33064:3306